### ISSUE TITLE
Wonderful and very helpful project

### ISSUE THREAD

**Issue by coho-salmon** [BurninLeo/see-non-printable-characters#1]
Thank you for this project and your web page. This is very useful to me, and surprisingly hard to find as an Android app.
(And I hope it's appropriate to post this kind of comment here. I don't see any place for comments.)

**Comment by BurninLeo** [comment]
Kind feedback is always welcome, thank you :)

Good to hear that the script is as helpful as the number of requests suggested. If you are concerend with API stuff, you may also be interested in my newest tool: https://www.soscisurvey.de/tools/post-monkey.php (not yet on github)
