### ISSUE TITLE
Add link to the live tool in the repository's "website" field

### ISSUE THREAD

**Issue by waldyrious** [BurninLeo/see-non-printable-characters#3]
The way that the link to https://www.soscisurvey.de/tools/view-chars.php is aliased as simply soscisurvey.de in the README, and the phrasing of the sentence on which it is included, makes it unclear that one can click it to open the tool itself.

I would suggest at least adding the link to the repository's "website" field (in the repository settings), and perhaps also rephrasing the README sentence to say something like

> This repository is the source code for the tool that can be accessed online at https://www.soscisurvey.de/tools/view-chars.php

WDYT?

**Comment by BurninLeo** [comment]
I think you're absolutely right, thanks for pointing out. The README has been updated.
